default:
  image: stunts/structure_threader_ci:001

variables:
  APPTAINER_OPTS: "--fakeroot"

stages:
  - tests
  - deployment

# Static Application Security Testing (SAST)
sast:
  stage: tests
include:
- template: Security/SAST.gitlab-ci.yml


# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  ST_INSTALL_BINARIES: "True"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  SAST_EXCLUDED_PATHS: "venv/"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

tests:
    stage: tests
    script:
      - python -V               # Print out python version for debugging
      - pip install virtualenv
      - virtualenv venv
      - source venv/bin/activate
      - pip install pytest
      - pip install .
      - pytest tests/*.py -v
      - tests/structure_field_test.sh
      - tests/fastStructure_field_test.sh
      - tests/maverick_field_test.sh
      - tests/alstructure_field_tests.sh
      - tests/neuraladmixture_field_tests.sh


deployment:
    stage: deployment
    script:
        - python -V
        - pip install virtualenv
        - virtualenv venv
        - source venv/bin/activate
        - pip install build twine
        - python -m build
        - twine upload dist/* -u __token__ -p $pypi_token
    only:
        - tags
    artifacts:
        name: "$CI_PROJECT_NAME-$CI_COMMIT_TAG"
        paths:
            - dist/
