# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml

# Use python 3.6 to work around a RTD bug (https://github.com/readthedocs/readthedocs.org/issues/5474)
python:
  version: 3.6
  install:
    - requirements: docs/requirements.txt
