site_name: 'Structure_threader manual'
#site_favicon: 'assets/Icon.png'
site_author: Francisco Pina-Martins
repo_url: https://gitlab.com/StuntsPT/Structure_threader
edit_uri: tree/master/docs

pages:
    - 'Introduction': 'index.md'
    - 'Installation & dependencies': 'install.md'
    - 'External programs': 'external.md'
    - 'Usage': 'usage.md'
    - 'Output': 'output.md'
    - 'Test Data': 'test_data.md'
    - 'Building Binaries': 'binaries.md'
    - 'Benchmarking': 'benchmark.md'
    - 'Citation': 'citation.md'
    - 'Future Plans': 'future.md'
    - 'FAQ': 'faq.md'
theme: readthedocs
